# Generated by Django 3.2.7 on 2021-09-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='title',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='typeofitem',
            field=models.CharField(max_length=200),
        ),
    ]
